# Generated by Django 6.1.1 on 2026-10-06 11:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowerrequest',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__gt', models.F('pickup_date'))), name='due_date_after_pickup_date'),
        ),
    ]
