# Generated by Django 6.1.1 on 2026-10-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_borrowerrequest_due_date_after_pickup_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerrequest',
            name='purpose',
            field=models.TextField(),
        ),
    ]
