# Generated by Django 6.1.1 on 2026-10-08 04:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('requests', '0004_remove_borrowerrequest_due_date_after_pickup_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BorrowerRequest',
            new_name='BorrowRequest',
        ),
    ]
